### ISSUE TITLE
fine_tune() 과 fit_one_cycle()의 차이가 뭔가요?

### ISSUE THREAD

**Issue by dooli1971039** [ttop32/KoGPT2novel#1]
코드를 보면 함수가 두개있던데 무슨 차이인지 궁금합니다.
하나는 왜 주석처리 하셨나요?

learn.fit_one_cycle(5, lr)
# learn.fine_tune(3)

**Comment by ttop32** [comment]
그냥 둘다 돌려보고 정확도 좋은 모델 쓸려고 했었습니다

차이점은 아래 링크 참고 하세요
https://forums.fast.ai/t/fine-tune-vs-fit-one-cycle/66029/7
